apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /nfsfileshare 
    server: master.openshift.paas-enablement.net
  persistentVolumeReclaimPolicy: Recycle 
